# Generated by Django 4.1 on 2022-12-01 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('delta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaBotanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_num', models.IntegerField()),
                ('camas', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='farm.campo')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo_name', models.CharField(max_length=64)),
                ('precio_por_cama', models.IntegerField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='farm.campo')),
                ('familia_botanica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='farm.familiabotanica')),
            ],
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_plantacion', models.DateField()),
                ('tiempo_crecimiento', models.IntegerField()),
                ('camas_requeridas', models.IntegerField()),
                ('cama', models.IntegerField(default=-1)),
                ('active', models.BooleanField(default=True)),
                ('bloque_num', models.IntegerField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='farm.cultivo')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='farm.sector')),
            ],
            options={
                'ordering': ['cultivo', 'bloque_num'],
            },
        ),
    ]
