# Generated by Django 4.1 on 2022-10-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivos',
            name='precio_por_cama',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
