# Generated by Django 4.1 on 2022-10-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_cultivos_precio_por_cama'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloques',
            new_name='Bloque',
        ),
        migrations.RenameModel(
            old_name='Cultivos',
            new_name='Cultivo',
        ),
    ]
