# Generated by Django 4.1 on 2022-10-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_bloque_dia_finalizar_remove_bloque_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloque',
            old_name='dia_planatacion',
            new_name='dia_plantacion',
        ),
    ]
